title: Ivar The Boneless Blog
description: Personal blog about Threat Intelligence and Malware analysis
show_downloads: false
theme: jekyll-theme-midnight
author: Ivar The Boneless
url:

footer-links:
  email: ivar_the_boneless@tuta.io
  github: IvarTheBoneless25
  twitter: IvarThe29191612

footer_links:
  - title: Mail
    url: ivar_the_boneless@tuta.io
    icon: fab fa-twitter
  - title: Twitter
    url: https://twitter.com/IvarThe29191612
    icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/IvarTheBoneless25
    icon: fab fa-github
    
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true