title: Ivar The Boneless Blog
description: Personal blog about Threat Intelligence and Malware analysis
show_downloads: false
theme: jekyll-theme-midnight
author: Ivar The Boneless
url:

sass:
    style: compressed
    
footer-links:
  email: ivar_the_boneless@tuta.io
  github: IvarTheBoneless25
  twitter: IvarThe29191612
    
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true